const {
  GITHUB_ORG_NAME_SSM,
  GITHUB_ORG_TOKEN_SSM,
  GITHUB_ORG_HOOK_ID_SSM,
  GITHUB_ORG_RUNNER_TOKEN_SSM,
  API_URL,
  API_SECRET,
  CLUSTER_NAME,
  CLUSTER_SERVICE_NAME,
} = process.env;

module.exports = {
  GITHUB_ORG_NAME_SSM,
  GITHUB_ORG_TOKEN_SSM,
  GITHUB_ORG_HOOK_ID_SSM,
  GITHUB_ORG_RUNNER_TOKEN_SSM,
  API_URL,
  API_SECRET,
  CLUSTER_NAME,
  CLUSTER_SERVICE_NAME,
};
